[package]
name = "tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "matrix-workspace-tui"
path = "src/main.rs"

[dependencies]
api-client = { path = "../api-client" }
state = { path = "../state" }
tokio.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
httpmock.workspace = true
tempfile.workspace = true
